app/categories/urls.py
from . import views
from django.urls import path

app_name = 'categories'

urlpatterns = [

    path('', views.CategoryListView.as_view(), name='list'),
    path('create', views.CategoryCreateView.as_view(), name='create'),
    path('update/<int:pk>', views.CategoryUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', views.CategoryDeleteView.as_view(), name='delete'),

]

app/core/urls.py
from . import views
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    # Admin
    path('admin/', admin.site.urls),

    # Basic
    path('', views.HomeView.as_view(), name='home'),
    path('faq/', views.FAQView.as_view(), name='f-a-q'),

    # Apps
    path('tasks/', include('tasks.urls')),
    path('workers/', include('workers.urls')),
    path('accounts/', include('accounts.urls')),
    path('management/', include('management.urls')),
    path('categories/', include('categories.urls')),
    path('educations/', include('educations.urls')),
    path('presentation', views.PresentationView.as_view(), name='presentation'),
]

if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/management/urls.py
from . import views
from django.urls import path

app_name = 'management'

urlpatterns = [
    path('dashboard', views.DashboardView.as_view(), name='dashboard'),
    path('task-assigner', views.AssignTasksView.as_view(), name='task-assigner'),
    path('matching-result', views.MatchingResultView.as_view(), name='matching-result'),
    path('matching-history', views.MatchingHistoryView.as_view(), name='matching-history'),
    path('contact-us', views.contact_us_view, name='contact-us'),
]

app/categories/models.py
from django.db import models
from django.contrib.auth.models import User


class Category(models.Model):
    name = models.CharField(max_length=255, blank=True, null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    created_on_datetime = models.DateTimeField(auto_now_add=True, db_index=True)
    updated_on_datetime = models.DateTimeField(auto_now=True, db_index=True)

    def __str__(self):
        return f'{self.name}'

app/categories/forms.py
from django import forms
from categories.models import Category


class CategoryForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['name'].widget = forms.TextInput(attrs={
            'class': 'form-control',
            'type': 'text',
            'name': 'name',
            'id': 'name',
        })

    class Meta:
        model = Category
        fields = ['name']

app/categories/views.py
from django.urls import reverse
from django.views import generic
from categories.models import Category
from categories.forms import CategoryForm
from django.http import HttpResponseRedirect
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required


@method_decorator(login_required, name='dispatch')
class CategoryListView(generic.ListView):
    model = Category
    template_name = "category/list-categories.html"

    def get_queryset(self):
        qs = super().get_queryset()
        qs = qs.filter(user=self.request.user).order_by('created_on_datetime')
        return qs


@method_decorator(login_required, name='dispatch')
class CategoryCreateView(generic.CreateView):
    model = Category
    form_class = CategoryForm
    template_name = "category/create-category.html"

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())

    def get_success_url(self):
        return reverse("categories:list")


@method_decorator(login_required, name='dispatch')
class CategoryUpdateView(generic.UpdateView):
    model = Category
    form_class = CategoryForm
    template_name = "category/update-category.html"
    context_object_name = 'category'

    def get_queryset(self):
        qs = super().get_queryset()
        qs = qs.filter(user=self.request.user)
        return qs

    def get_success_url(self):
        return reverse('categories:list')


@method_decorator(login_required, name='dispatch')
class CategoryDeleteView(generic.DeleteView):
    model = Category
    template_name = "category/delete-category.html"
    context_object_name = 'category'

    def get_queryset(self):
        qs = super().get_queryset()
        qs = qs.filter(user=self.request.user)
        return qs

    def get_success_url(self):
        return reverse("categories:list")

app/templates/category/create-category.html
{% extends "dashboard-base.html" %}


{% block content %}

    <main id="main" class="main">
        <div class="pagetitle">
            <h1>Category Form</h1>
            <nav>
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href={% url 'home' %}>Home</a></li>
                    <li class="breadcrumb-item"><a href={% url 'management:dashboard' %}>Dashobard</a></li>
                    <li class="breadcrumb-item"><a href={% url 'categories:list' %}>Categories</a></li>
                    <li class="breadcrumb-item active">New Category</li>
                </ol>
            </nav>
        </div>

        <section class="section">
            <div class="row">
                <div class="col-lg-2"></div>
                <div class="col-lg-8">

                    <div class="card">
                        <div class="card-body">
                            <h5 class="card-title">New Category</h5>

                            <!-- General Form Elements -->
                            <form method="post">
                                {% csrf_token %}

                                <div class="row mb-3">
                                    <label for="inputText" class="col-sm-2 col-form-label">Name</label>
                                    <div class="col-sm-10">
                                        {{ form.name }}
                                    </div>
                                </div>

                                <div class="row mb-3">
                                    <label class="col-sm-2 col-form-label"></label>
                                    <div class="col-sm-10">
                                        <button type="submit" class="btn btn-primary">Submit</button>
                                    </div>
                                </div>

                            </form>

                        </div>
                    </div>

                </div>
            </div>
        </section>

    </main>

{% endblock content %}

app/templates/category/delete-category.html
{% extends "dashboard-base.html" %}


{% block content %}

    <main id="main" class="main">

        <div class="pagetitle">

            <nav>
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href={% url 'home' %}>Home</a></li>
                    <li class="breadcrumb-item"><a href={% url 'management:dashboard' %}>Dashobard</a></li>
                    <li class="breadcrumb-item"><a href={% url 'categories:list' %}>Categories</a></li>
                    <li class="breadcrumb-item active">Delete</li>
                    <li class="breadcrumb-item active">{{ category.name }}</li>
                </ol>
            </nav>
        </div><!-- End Page Title -->

        <section class="section">
            <div class="row">
                <div class="col-lg-9">
                    <div class="card">
                        <div class="card-body">
                            <h5 class="card-title"><i class="bi bi-trash-fill"></i> Delete Category</h5>
                            <p>Are you sure you want to delete category {{ category.name }}</p>

                            <form method="POST">
                                {% csrf_token %}
                                <input type="submit" class="btn btn-danger" data-bs-toggle="modal"
                                       data-bs-target="#basicModal" value="Delete Category"/>
                                &nbsp;
                                &nbsp;
                                &nbsp;
                                &nbsp;
                                &nbsp;

                                <a href="{% url 'categories:list' %}"
                                   class="btn btn-primary">
                                    Back to Table
                                </a>

                            </form>
                        </div>
                    </div>
                </div>

            </div>
        </section>

    </main><!-- End #main -->


{% endblock content %}

app/templates/category/list-categories.html
{% extends "dashboard-base.html" %}


{% block content %}

    <main id="main" class="main">
        <div class="pagetitle">
            <h1>Categories Table</h1>
            <nav>
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href={% url 'home' %}>Home</a></li>
                    <li class="breadcrumb-item"><a href={% url 'management:dashboard' %}>Dashobard</a></li>

                    <li class="breadcrumb-item active">Categories</li>
                </ol>
            </nav>
        </div><!-- End Page Title -->

        <section class="section">
            <div class="row">
                <div class="col-lg-12">
                    <div class="card">
                        <div class="card-body">
                            <h5 class="card-title">Categories</h5>
                            <a href="{% url 'categories:create' %}">
                                <button type="submit" class="btn btn-primary">Add New Category</button>
                            </a>
                            <br>
                            <br>

                            <!-- Table with stripped rows -->
                            <table class="table datatable">
                                <thead>
                                <tr>
                                    <th scope="col" data-sortable="false">#</th>
                                    <th scope="col" data-sortable="false">Name</th>
                                    <th scope="col" data-sortable="false">Actions</th>
                                </tr>
                                </thead>
                                <tbody>
                                {% for category in object_list %}
                                    <tr>
                                        <th scope="row">{{ category.id }}</th>
                                        <td>{{ category.name }}</td>
                                        <td>
                                            <a href={% url 'categories:update' category.id %}>
                                                <i class="bi bi-pencil-fill"></i></a>&nbsp;&nbsp;

                                            <a href={% url 'categories:delete' category.id %}>
                                                <i class="bi bi-trash-fill"></i></a>
                                        </td>
                                    </tr>
                                {% endfor %}

                                </tbody>
                            </table>
                            <!-- End Table with stripped rows -->

                        </div>
                    </div>

                </div>
            </div>
        </section>

    </main><!-- End #main -->

{% endblock content %}

app/templates/category/list-category.html
{% extends "dashboard-base.html" %}


{% block content %}

    <main id="main" class="main">
        <div class="pagetitle">
            <h1>Categories Table</h1>
            <nav>
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href={% url 'home' %}>Home</a></li>
                    <li class="breadcrumb-item active">Data Table</li>
                </ol>
            </nav>
        </div><!-- End Page Title -->

        <section class="section">
            <div class="row">
                <div class="col-lg-12">
                    <div class="card">
                        <div class="card-body">
                            <h5 class="card-title">Datatables</h5>
                            <a href="{% url 'categories:create' %}">
                                <button type="submit" class="btn btn-primary">Add New Category</button>
                            </a>
                            <br>
                            <br>

                            <!-- Table with stripped rows -->
                            <table class="table datatable">
                                <thead>
                                <tr>
                                    <th scope="col" data-sortable="false">#</th>
                                    <th scope="col" data-sortable="false">Department</th>
                                    <th scope="col" data-sortable="false">Category</th>
                                    <th scope="col" data-sortable="false">Actions</th>
                                </tr>
                                </thead>
                                <tbody>
                                <tr>
                                    <th scope="row">1</th>
                                    <td>Software</td>
                                    <td>ASP.NET Developer</td>
                                    <td>
                                        <a href={% url 'categories:update' 3 %}> <i class="bi bi-pencil-fill"></i></a>&nbsp;&nbsp;
                                        <a href={% url 'categories:delete' 3 %}> <i class="bi bi-trash-fill"></i></a>
                                    </td>
                                </tr>

                                <tr>
                                    <th scope="row">2</th>
                                    <td>Software</td>
                                    <td>Django Developer</td>
                                    <td>
                                        <a href={% url 'categories:update' 3 %}> <i class="bi bi-pencil-fill"></i></a>&nbsp;&nbsp;
                                        <a href={% url 'categories:delete' 3 %}> <i class="bi bi-trash-fill"></i></a>
                                    </td>
                                </tr>

                                <tr>
                                    <th scope="row">3</th>
                                    <td>Accountant</td>
                                    <td>Reviewer</td>
                                    <td>
                                        <a href={% url 'categories:update' 3 %}> <i class="bi bi-pencil-fill"></i></a>&nbsp;&nbsp;
                                        <a href={% url 'categories:delete' 3 %}> <i class="bi bi-trash-fill"></i></a>
                                    </td>
                                </tr>
                                </tbody>
                            </table>
                            <!-- End Table with stripped rows -->

                        </div>
                    </div>

                </div>
            </div>
        </section>

    </main><!-- End #main -->

{% endblock content %}

app/templates/category/update-category.html
{% extends "dashboard-base.html" %}


{% block content %}

    <main id="main" class="main">

        <div class="pagetitle">
            <h1>Category Form</h1>
            <nav>
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href={% url 'home' %}>Home</a></li>
                    <li class="breadcrumb-item"><a href={% url 'management:dashboard' %}>Dashobard</a></li>
                    <li class="breadcrumb-item"><a href={% url 'categories:list' %}>Categories</a></li>
                    <li class="breadcrumb-item active">Update Category</li>
                    <li class="breadcrumb-item active">{{ form.name.value }}</li>
                </ol>
            </nav>
        </div><!-- End Page Title -->

        <section class="section">
            <div class="row">
                <div class="col-lg-2"></div>
                <div class="col-lg-8">

                    <div class="card">
                        <div class="card-body">
                            <h5 class="card-title">Update Category</h5>

                            <form method="POST">
                                {% csrf_token %}
                                <div class="row mb-3">
                                    <label for="inputText" class="col-sm-2 col-form-label">Name</label>
                                    <div class="col-sm-10">
                                        {{ form.name }}
                                    </div>
                                </div>


                                <div class="row mb-3">
                                    <label class="col-sm-2 col-form-label"></label>
                                    <div class="col-sm-10">
                                        <button type="submit" class="btn btn-primary">Update</button>
                                    </div>
                                </div>

                            </form>

                        </div>
                    </div>

                </div>
            </div>
        </section>

    </main><!-- End #main -->


{% endblock content %}