app/core/urls.py
from . import views
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    # Admin
    path('admin/', admin.site.urls),

    # Basic
    path('', views.HomeView.as_view(), name='home'),
    path('faq/', views.FAQView.as_view(), name='f-a-q'),

    # Apps
    path('tasks/', include('tasks.urls')),
    path('workers/', include('workers.urls')),
    path('accounts/', include('accounts.urls')),
    path('management/', include('management.urls')),
    path('categories/', include('categories.urls')),
    path('educations/', include('educations.urls')),
    path('presentation', views.PresentationView.as_view(), name='presentation'),
]

if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/management/urls.py
from . import views
from django.urls import path

app_name = 'management'

urlpatterns = [
    path('dashboard', views.DashboardView.as_view(), name='dashboard'),
    path('task-assigner', views.AssignTasksView.as_view(), name='task-assigner'),
    path('matching-result', views.MatchingResultView.as_view(), name='matching-result'),
    path('matching-history', views.MatchingHistoryView.as_view(), name='matching-history'),
    path('contact-us', views.contact_us_view, name='contact-us'),
]

app/tasks/urls.py
from . import views
from django.urls import path

app_name = 'tasks'

urlpatterns = [

    path('', views.TaskListView.as_view(), name='list'),
    path('create', views.TaskCreateView.as_view(), name='create'),
    path('<str:pk>', views.TaskDetailsView.as_view(), name='details'),
    path('update/<str:pk>', views.TaskUpdateView.as_view(), name='update'),
    path('delete/<str:pk>', views.TaskDeleteView.as_view(), name='delete'),

]

app/workers/urls.py
from . import views
from django.urls import path

app_name = 'workers'

urlpatterns = [
    path('', views.WorkerListView.as_view(), name='list'),
    path('create', views.WorkerCreateView.as_view(), name='create'),
    path('<str:pk>', views.WorkerDetailsView.as_view(), name='details'),
    path('update/<str:pk>', views.WorkerUpdateView.as_view(), name='update'),
    path('delete/<str:pk>', views.WorkerDeleteView.as_view(), name='delete'),
]

app/management/models.py
from django.db import models
from django.contrib.auth.models import User


class HeuristicMatching(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=False, blank=False)
    heuristic_matching_edges = models.JSONField(null=True, blank=True)
    execution_time = models.FloatField(null=False, blank=False)
    heuristic_matching = models.IntegerField(null=False, blank=False)
    created_on_datetime = models.DateTimeField(auto_now_add=True, db_index=True)
    updated_on_datetime = models.DateTimeField(auto_now=True, db_index=True)

    def __str__(self):
        return f'{self.heuristic_matching} took {self.execution_time}'


class MaxMatching(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=False, blank=False)
    max_matching_edges = models.JSONField(null=True, blank=True)
    execution_time = models.FloatField(null=False, blank=False)
    max_matching = models.IntegerField(null=False, blank=False)
    created_on_datetime = models.DateTimeField(auto_now_add=True, db_index=True)
    updated_on_datetime = models.DateTimeField(auto_now=True, db_index=True)

    def __str__(self):
        return f'{self.max_matching} took {self.execution_time}'


class ExecutionHistory(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=False, blank=False)
    max_matching = models.ForeignKey(MaxMatching, on_delete=models.CASCADE, null=True, blank=True)
    heuristic_matching = models.ForeignKey(HeuristicMatching, on_delete=models.CASCADE, null=True, blank=True)
    graph_density = models.FloatField(null=False, blank=False)
    created_on_datetime = models.DateTimeField(auto_now_add=True, db_index=True)
    updated_on_datetime = models.DateTimeField(auto_now=True, db_index=True)

    def __str__(self):
        return f'History heuristic: {self.heuristic_matching} -- max-matching {self.max_matching}'


class ContactUs(models.Model):
    name = models.CharField(max_length=100, null=False, blank=False)
    email = models.EmailField(null=False, blank=False)
    subject = models.CharField(max_length=255, null=False, blank=False)
    message = models.TextField(null=False, blank=False)

app/management/forms.py
from django import forms
from management.models import ContactUs


class ContactUsForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['name'].widget = forms.TextInput(attrs={
            'class': 'form-control',
            'type': 'text',
            'name': 'name',
            'id': 'name',
            'placeholder': "Your Name"
        })

        self.fields['email'].widget = forms.EmailInput(attrs={
            'class': 'form-control',
            'type': 'email',
            'name': 'email',
            'id': 'email',
            'placeholder': "Your Email"
        })

        self.fields['subject'].widget = forms.TextInput(attrs={
            'class': 'form-control',
            'type': 'text',
            'name': 'subject',
            'id': 'subject',
            'placeholder': "Subject"
        })

        self.fields['message'].widget = forms.Textarea(attrs={
            'class': 'form-control',
            'type': 'text',
            'name': 'message',
            'id': 'message',
            'rows': "5",
            'placeholder': "Message"
        })

    class Meta:
        model = ContactUs
        fields = "__all__"

app/management/views.py
import json
from time import sleep

from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth.mixins import UserPassesTestMixin
from django.http import HttpResponse, JsonResponse
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.views import generic, View

from management.forms import ContactUsForm
from management.models import ContactUs
from management.services import Services
from src.graph.bipartite_graph import BipartiteGraph
from src.solvers.max_matching.heuristics.random_greedy.monte_carlo import MonteCarlo
from tasks.selectors import TaskSelectors
from workers.selectors import WorkerSelectors
from django.shortcuts import render, redirect
from management.selectors import ManagementSelectors


@method_decorator(login_required, name='dispatch')
class DashboardView(View):
    template_name = "management/dashboard.html"

    def get(self, request, *args, **kwargs):
        user = request.user
        workers_count = ManagementSelectors.get_workers_count(user)
        tasks_count = ManagementSelectors.get_tasks_count(user)
        categories_count = ManagementSelectors.get_categories_count(user)
        educations_count = ManagementSelectors.get_educations_count(user)

        tasks_per_category = ManagementSelectors.get_tasks_per_category(user)
        workers_per_category = ManagementSelectors.get_workers_per_category(user)
        top_workers = ManagementSelectors.get_top_workers(user)
        top_categories = ManagementSelectors.get_top_categories(user)

        context = {
            'workers_count': workers_count,
            'tasks_count': tasks_count,
            'categories_count': categories_count,
            'educations_count': educations_count,
            'tasks_per_category': json.dumps(tasks_per_category),
            'workers_per_category': json.dumps(workers_per_category),
            'top_5_workers': top_workers,
            'top_10_categories': top_categories,
        }
        return render(request, f"{self.template_name}", context=context)


@method_decorator(login_required, name='dispatch')
class AssignTasksView(View):
    template_name = "management/task-assigner.html"

    @staticmethod
    def get_context(request):
        tasks_counts_dict = TaskSelectors.get_tasks_count_by_status(request.user)
        workers_counts_dict = WorkerSelectors.get_workers_count_by_status(request.user)

        context = {
            'open_tasks': tasks_counts_dict['OPEN'],
            'progress_tasks': tasks_counts_dict['PROGRESS'],
            'done_tasks': tasks_counts_dict['DONE'],

            'free_workers': workers_counts_dict['FREE'],
            'occupied_workers': workers_counts_dict['OCCUPIED'],

        }

        return context

    def get(self, request, *args, **kwargs):
        context = self.get_context(request)
        return render(request, f"{self.template_name}", context=context)

    def post(self, request, *args, **kwargs):
        action = request.POST.get("action", "")
        action_func = Services.get_task_assigner_action_func(action)
        action_func(request=request)

        if action == 'execute_algorithm':
            return redirect(reverse('management:matching-history'))
        else:
            context = self.get_context(request)
            return render(request, f"{self.template_name}", context)


@method_decorator(login_required, name='dispatch')
class MatchingHistoryView(generic.ListView):
    template_name = "management/matching-history.html"

    @staticmethod
    def get_context(request):
        context = ManagementSelectors.get_last_10_execution_history_statistics(user=request.user)
        return context

    def get(self, request, *args, **kwargs):
        context = self.get_context(request)
        return render(request, f"{self.template_name}", context=context)


@method_decorator(login_required, name='dispatch')
class MatchingResultView(View):
    template_name = "management/matching-result.html"

    @staticmethod
    def get_context(request):
        context = ManagementSelectors.get_last_matching_result(user=request.user)
        return context

    def get(self, request, *args, **kwargs):
        context = self.get_context(request)
        return render(request, f"{self.template_name}", context=context)


def contact_us_view(request):
    if request.method == 'POST':
        form = ContactUsForm(request.POST)
        if form.is_valid():
            form.save()
            success_message = "Your message has been sent. Thank you!"
            context = {'form': form, 'message': success_message}
            return render(request, 'management/contact-us.html', context)
    else:
        form = ContactUsForm()
        return render(request, 'management/contact-us.html', {'form': form})

app/templates/management/contact-us.html
{% extends "site-base.html" %}
{% load static %}


{% block content %}

    <main id="main" class="main">
        <!-- ======= Contact Section ======= -->

        <section id="contact" class="contact" style="margin-top: 5%;">
            <div class="container">

                <div class="section-title" data-aos="fade-up">
                    <h2>Contact Us</h2>
                </div>

                <div class="row" style="margin-top: 10%;">

                    <div class="col-lg-4 col-md-6" data-aos="fade-up" data-aos-delay="100">
                        <div class="contact-about">
                            <h4>Reach Out to Our Dedicated Team</h4>
                            <p>
                                Contact Us - Reach Out to Our Dedicated Team
                                We value your feedback, inquiries, and collaboration opportunities. Our dedicated team
                                at Max-Matching is here to assist you in every way possible. Whether you have
                                questions about our products, services, or you're seeking partnership opportunities,
                                we're just a message away.</p>

                        </div>
                    </div>

                    <div class="col-lg-3 col-md-6 mt-4 mt-md-0" data-aos="fade-up" data-aos-delay="200">
                        <div class="info">
                            <div>
                                <i class="ri-map-pin-line"></i>
                                <p>Dubai- Al Maarifa Village <br> office F02- 1st Block13</p>

                            </div>

                            <div>
                                <i class="ri-mail-send-line"></i>
                                <p>tc_dubai@svuonline.org</p>
                            </div>

                            <div>
                                <i class="ri-phone-line"></i>
                                <p>+971 555538531</p>
                            </div>

                        </div>
                    </div>

                    <div class="col-lg-5 col-md-12" data-aos="fade-up" data-aos-delay="300">
                        <form action="{% url 'management:contact-us' %}" method="post">

                            {% csrf_token %}
                            <div class="form-group">
                                {{ form.name }}

                            </div>
                            <br>
                            <div class="form-group">
                                {{ form.email }}
                            </div>
                            <br>
                            <div class="form-group">
                                {{ form.subject }}
                            </div>
                            <br>
                            <div class="form-group">
                                {{ form.message }}
                            </div>
                            <br>
                            <div class="my-3">
                                {% if message %}
                                    <div class="alert alert-primary bg-primary text-light border-0 alert-dismissible fade show"
                                         role="alert">
                                        {{ message }}
                                        <button type="button" class="btn-close btn-close-white" data-bs-dismiss="alert"
                                                aria-label="Close"></button>
                                    </div>
                                {% endif %}
                            </div>
                            <div class="text-center">
                                <button class="btn btn-primary" type="submit">Send Message</button>
                            </div>
                        </form>
                    </div>

                </div>

            </div>
        </section><!-- End Contact Section -->


    </main>


{% endblock content %}

app/templates/management/matching-result.html
{% extends "dashboard-base.html" %}
{% load static %}

{% block content %}

    <main id="main" class="main">
        <div class="pagetitle">
            <h1>Matching Result</h1>
            <nav>
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href={% url 'home' %}>Home</a></li>
                    <li class="breadcrumb-item"><a href={% url 'management:dashboard' %}>Dashobard</a></li>
                    <li class="breadcrumb-item active">Matching Table</li>
                </ol>
            </nav>
        </div><!-- End Page Title -->

        <section class="section">
            <div class="row">
                <div class="col-lg-12">
                    <div class="card">
                        <div class="card-body">
                            <table class="table datatable">
                                <thead>
                                <tr>
                                    <th id="#worker-table-thead" scope="col">Worker</th>
                                    <th id="#img-table-thead">Relation</th>
                                    <th id="#task-table-thead" scope="col">Task</th>
                                </tr>
                                </thead>

                                <tbody>
                                {% for row in rows %}
                                    <tr>
                                        <td class="text-primary ">

                                            <a href={% url 'workers:details' row.1 %}>
                                                <img
                                                        src="{% static 'img/worker-icon.png' %}"
                                                        style="height: 35px; width: 45px"
                                                        alt="">

                                                {{ row.0 }}
                                            </a>
                                        </td>
                                        <td>
                                            <i style=" font-size: 30px" class="bi bi-arrow-left-right"></i>
                                        </td>
                                        <td class="text-primary ">
                                            <a href={% url 'tasks:details' row.2 %}>
                                                <img
                                                        src="{% static 'img/task-icon.png' %}"
                                                        style="height: 40px; width: 40px"
                                                        alt="">
                                                {{ row.3 }}
                                            </a>
                                        </td>
                                    </tr>
                                {% endfor %}

                                </tbody>
                            </table>
                        </div>
                    </div>

                </div>
            </div>
        </section>

    </main><!-- End #main -->


{% endblock content %}

app/templates/management/task-assigner.html
{% extends "dashboard-base.html" %}
{% load static %}

{% block content %}
    <main id="main" class="main">
        <div class="pagetitle">
            <h1>Task Assignment</h1>
            <nav>
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href={% url 'home' %}>Home</a></li>
                    <li class="breadcrumb-item"><a href={% url 'management:dashboard' %}>Dashobard</a></li>
                    <li class="breadcrumb-item active">Task Assigner</li>
                </ol>
            </nav>
        </div>

        <section class="section dashboard">
            <div class="row">
                <h4>Workers</h4>

                <div class="col-xxl-4 col-md-4">
                    <div class="card info-card sales-card">
                        <div class="card-body">
                            <h5 class="card-title">Free<span></span></h5>
                            <div class="d-flex align-items-center">
                                <div class="card-icon rounded-circle d-flex align-items-center justify-content-center">
                                    <i class="bi bi-person-fill"></i>
                                </div>
                                <div class="ps-3">
                                    <h6>{{ free_workers }}</h6>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-xxl-2 col-md-2"></div>
                <div class="col-xxl-4 col-md-4">
                    <div class="card info-card sales-card">
                        <div class="card-body">
                            <h5 class="card-title">Occupied<span></span></h5>
                            <div class="d-flex align-items-center">
                                <div class="card-icon rounded-circle d-flex align-items-center justify-content-center">
                                    <i class="bi bi-person-workspace"></i>
                                </div>
                                <div class="ps-3">
                                    <h6>{{ occupied_workers }}</h6>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-xxl-1 col-md-2"></div>
            </div>
            <br>
            <div class="row">
                <h4>Tasks</h4>
                <div class="col-xxl-4 col-md-4">
                    <div class="card info-card sales-card">
                        <div class="card-body">
                            <h5 class="card-title">Open<span></span></h5>
                            <div class="d-flex align-items-center">
                                <div class="card-icon rounded-circle d-flex align-items-center justify-content-center">
                                    <i class="bi bi-hourglass-top"></i></div>
                                <div class="ps-3">
                                    <h6>{{ open_tasks }}</h6>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-xxl-4 col-md-4">
                    <div class="card info-card sales-card">
                        <div class="card-body">
                            <h5 class="card-title">Progress<span></span></h5>
                            <div class="d-flex align-items-center">
                                <div class="card-icon rounded-circle d-flex align-items-center justify-content-center">
                                    <i class="bi bi-hourglass-split"></i>
                                </div>
                                <div class="ps-3">
                                    <h6>{{ progress_tasks }}</h6>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-xxl-4 col-md-4">
                    <div class="card info-card sales-card">
                        <div class="card-body">
                            <h5 class="card-title">Done<span></span></h5>
                            <div class="d-flex align-items-center">
                                <div class="card-icon rounded-circle d-flex align-items-center justify-content-center">
                                    <i class="bi bi-hourglass-bottom"></i></div>
                                <div class="ps-3">
                                    <h6>{{ done_tasks }}</h6>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <br>
            <br>
            {#            <div class="row">#}
            {#                <h4>Last Execution Result</h4>#}
            {#                <div class="col-xxl-4 col-md-4">#}
            {#                    <div class="card info-card sales-card">#}
            {#                        <div class="card-body">#}
            {#                            <h5 class="card-title">Density<span></span></h5>#}
            {#                            <div class="d-flex align-items-center">#}
            {#                                <div class="card-icon rounded-circle d-flex align-items-center justify-content-center">#}
            {#                                    <i class="bi bi-percent"></i>#}
            {#                                </div>#}
            {#                                <div class="ps-3">#}
            {#                                    <h6 class="text-danger">{{ graph_density }}</h6>#}
            {#                                </div>#}
            {#                            </div>#}
            {#                        </div>#}
            {#                    </div>#}
            {#                </div>#}
            {#                <div class="col-xxl-4 col-md-4">#}
            {#                    <div class="card info-card sales-card">#}
            {#                        <div class="card-body">#}
            {#                            <h5 class="card-title">Execution Time<span></span></h5>#}
            {#                            <div class="d-flex align-items-center">#}
            {#                                <div class="card-icon rounded-circle d-flex align-items-center justify-content-center">#}
            {#                                    <i class="bi bi-alarm-fill"></i>#}
            {#                                </div>#}
            {#                                <div class="ps-3">#}
            {#                                    <h6 class="text-danger">#}
            {#                                        {% if execution_time %}#}
            {#                                            {{ execution_time }} s#}
            {#                                        {% else %}#}
            {#                                            None#}
            {#                                        {% endif %}#}
            {#                                    </h6>#}
            {#                                </div>#}
            {#                            </div>#}
            {#                        </div>#}
            {#                    </div>#}
            {#                </div>#}
            {#                <div class="col-xxl-4 col-md-4">#}
            {#                    <div class="card info-card sales-card">#}
            {#                        <div class="card-body">#}
            {#                            <h5 class="card-title">Matching Result<span></span></h5>#}
            {#                            <div class="d-flex align-items-center">#}
            {#                                <div class="card-icon rounded-circle d-flex align-items-center justify-content-center">#}
            {#                                    <i class="bi bi-intersect"></i>#}
            {#                                </div>#}
            {#                                <div class="ps-3">#}
            {#                                    <h6 class="text-danger">{{ matching }}</h6>#}
            {#                                </div>#}
            {#                            </div>#}
            {#                        </div>#}
            {#                    </div>#}
            {#                </div>#}
            {#            </div>#}
            <br>
            <br>
            <div class="row">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">Task Assignment Actions</h5>
                        <form method="post" action="{% url 'management:task-assigner' %}" class="row g-3">
                            {% csrf_token %}
                            <input type="hidden" id="actionValue" name="action" value="">
                            <div class="col-md-3">
                                <div class="d-grid gap-2 ">
                                    <button
                                            class="btn btn-warning"
                                            onclick="setActionValue('clear_assigned_tasks')"
                                            type="submit">
                                        Clear Assigned Tasks
                                    </button>
                                </div>
                            </div>
                            <div class="col-md-2">
                                <div class="d-grid gap-2 ">
                                    <button
                                            class="btn btn-danger"
                                            onclick="setActionValue('mark_tasks_done')"
                                            type="submit">
                                        Mark Tasks Done
                                    </button>
                                </div>
                            </div>
                            <div class="col-md-2"></div>
                            <div class="col-md-5">
                                <div class="d-grid gap-2 ">
                                    <button
                                            class="btn btn-primary"
                                            onclick="setActionValue('execute_algorithm')"
                                            type="submit">Execute Algorithm
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </section>
    </main>
    <script>
        function setActionValue(value) {
            document.getElementById('actionValue').value = value;
        }
    </script>
{% endblock content %}