app/core/urls.py
from . import views
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    # Admin
    path('admin/', admin.site.urls),

    # Basic
    path('', views.HomeView.as_view(), name='home'),
    path('faq/', views.FAQView.as_view(), name='f-a-q'),

    # Apps
    path('tasks/', include('tasks.urls')),
    path('workers/', include('workers.urls')),
    path('accounts/', include('accounts.urls')),
    path('management/', include('management.urls')),
    path('categories/', include('categories.urls')),
    path('educations/', include('educations.urls')),
    path('presentation', views.PresentationView.as_view(), name='presentation'),
]

if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/management/urls.py
from . import views
from django.urls import path

app_name = 'management'

urlpatterns = [
    path('dashboard', views.DashboardView.as_view(), name='dashboard'),
    path('task-assigner', views.AssignTasksView.as_view(), name='task-assigner'),
    path('matching-result', views.MatchingResultView.as_view(), name='matching-result'),
    path('matching-history', views.MatchingHistoryView.as_view(), name='matching-history'),
    path('contact-us', views.contact_us_view, name='contact-us'),
]

app/tasks/urls.py
from . import views
from django.urls import path

app_name = 'tasks'

urlpatterns = [

    path('', views.TaskListView.as_view(), name='list'),
    path('create', views.TaskCreateView.as_view(), name='create'),
    path('<str:pk>', views.TaskDetailsView.as_view(), name='details'),
    path('update/<str:pk>', views.TaskUpdateView.as_view(), name='update'),
    path('delete/<str:pk>', views.TaskDeleteView.as_view(), name='delete'),

]

app/tasks/models.py
import datetime

from django.conf import settings
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone


class Task(models.Model):
    class Status(models.Choices):
        OPEN = 'OPEN'
        DONE = 'DONE'
        PROGRESS = 'PROGRESS'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.dispatch_enabled = settings.DISPATCH_ENABLED

    title = models.CharField(max_length=50, null=False, blank=False)
    description = models.TextField(null=False, blank=False)
    deadline = models.DateField(default=datetime.date.today, null=True, blank=True)

    status = models.CharField(max_length=50, db_index=True, choices=Status.choices, default=Status.OPEN.value)

    categories = models.ManyToManyField('categories.Category', blank=True)
    educations = models.ManyToManyField('educations.Education', blank=True)

    assigned_to = models.ForeignKey("workers.Worker", on_delete=models.SET_NULL, blank=True, null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    created_on_datetime = models.DateTimeField(auto_now_add=True, db_index=True)
    updated_on_datetime = models.DateTimeField(auto_now=True, db_index=True)

    def __str__(self):
        return f'{self.title}'

app/tasks/forms.py
import datetime

from django import forms
from django.utils import timezone
from categories.models import Category
from educations.models import Education
from tasks.models import Task


class MultiSelectTagField(forms.ModelMultipleChoiceField):
    def label_from_instance(self, obj):
        return obj.name


class TaskForm(forms.ModelForm):
    # level = forms.ChoiceField(choices=Task.Level.choices)
    categories = MultiSelectTagField(required=False, queryset=Category.objects.all())
    educations = MultiSelectTagField(required=False, queryset=Education.objects.all())

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user')
        super().__init__(*args, **kwargs)

        self.fields['title'].widget = forms.TextInput(attrs={
            'class': 'form-control',
            'type': 'text',
            'name': 'title',
            'id': 'title',
        })

        self.fields['description'].widget = forms.Textarea(attrs={
            'class': 'form-control',
            'type': 'text',
            'name': 'description',
            'id': 'description',
        })

        self.fields['deadline'].widget = forms.TextInput(attrs={
            'class': 'form-control',
            'type': 'date',
            'name': 'deadline',
            'id': 'deadline',
        })

        self.fields['status'].widget = forms.Select(
            choices=Task.Status.choices,
            attrs={
                'class': 'form-control',
                'name': 'status',
                'id': 'status',
            })

        self.fields['categories'].widget = forms.SelectMultiple(
            choices=Category.objects.filter(user=user).values_list('id', 'name'),
            attrs={
                'class': 'form-control',
                'name': 'categories',
                'id': 'categories',
            })

        self.fields['educations'].widget = forms.SelectMultiple(
            choices=Education.objects.filter(user=user).values_list('id', 'name'),
            attrs={
                'class': 'form-control',
                'name': 'educations',
                'id': 'educations',
            })

    class Meta:
        model = Task
        exclude = ['user']

app/tasks/views.py
from tasks.models import Task
from django.urls import reverse
from tasks.forms import TaskForm
from django.views import generic
from django.shortcuts import render
from tasks.selectors import TaskSelectors
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required


@method_decorator(login_required, name='dispatch')
class TaskListView(generic.ListView):
    model = Task
    template_name = "tasks/list_tasks.html"

    def get_queryset(self):
        qs = super().get_queryset()
        qs = qs.filter(user=self.request.user).order_by('created_on_datetime')
        return qs


@method_decorator(login_required, name='dispatch')
class TaskCreateView(generic.CreateView):
    model = Task
    form_class = TaskForm
    template_name = "tasks/create_task.html"

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        print(form['deadline'])
        return super().form_valid(form)

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    def get_success_url(self):
        return reverse("tasks:list")


@method_decorator(login_required, name='dispatch')
class TaskUpdateView(generic.UpdateView):
    model = Task
    form_class = TaskForm
    template_name = "tasks/update_task.html"
    context_object_name = 'task'

    def get_queryset(self):
        qs = super().get_queryset()
        qs = qs.filter(user=self.request.user)
        return qs

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    def get_success_url(self):
        return reverse('tasks:list')


@method_decorator(login_required, name='dispatch')
class TaskDeleteView(generic.DeleteView):
    model = Task
    template_name = "tasks/delete_task.html"
    context_object_name = 'task'

    def get_queryset(self):
        qs = super().get_queryset()
        qs = qs.filter(user=self.request.user)
        return qs

    def get_success_url(self):
        return reverse("tasks:list")


@method_decorator(login_required, name='dispatch')
class TaskDetailsView(generic.DetailView):
    model = Task
    context_object_name = 'task'
    template_name = "tasks/task_details.html"

    def get_queryset(self):
        qs = super().get_queryset()
        qs = qs.filter(user=self.request.user)
        return qs

    def get(self, request, *args, **kwargs):
        obj: Task = self.get_object(queryset=self.get_queryset())
        context = TaskSelectors.get_task_details(task=obj)
        return render(request, f"{self.template_name}", context=context)

app/templates/tasks/create_task.html
{% extends "dashboard-base.html" %}


{% block content %}

    <main id="main" class="main">

        <div class="pagetitle">
            <h1>New Task</h1>
            <nav>
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href={% url 'home' %}>Home</a></li>
                    <li class="breadcrumb-item"><a href={% url 'management:dashboard' %}>Dashobard</a></li>
                    <li class="breadcrumb-item"><a href={% url 'tasks:list' %}>Tasks</a></li>
                    <li class="breadcrumb-item active">New Task</li>
                </ol>
            </nav>
        </div><!-- End Page Title -->

        <section class="section">
            <div class="row">
                <div class="col-lg-2"></div>
                <div class="col-lg-8">

                    <div class="card">
                        <div class="card-body">
                            <h5 class="card-title">New Task Form</h5>

                            <!-- General Form Elements -->
                            <form method="post">
                                {% csrf_token %}
                                <div class="row mb-3">
                                    <label for="inputText" class="col-sm-2 col-form-label">Title</label>
                                    <div class="col-sm-10">
                                        {{ form.title }}
                                    </div>
                                </div>
                                <div class="row mb-3">
                                    <label for="inputText" class="col-sm-2 col-form-label">Description</label>
                                    <div class="col-sm-10">
                                        {{ form.description }}
                                    </div>
                                </div>

                                <br>
                                <div class="row mb-3">
                                    <label for="inputDate" class="col-sm-2 col-form-label">Dead Line</label>
                                    <div class="col-sm-10">
                                        {{ form.deadline }}
                                    </div>
                                </div>
                                <br>


                                <br>
                                <fieldset class="row mb-3">
                                    <legend class="col-form-label col-sm-2 pt-0">Status</legend>
                                    <div class="col-sm-10">
                                        {{ form.status }}
                                    </div>
                                </fieldset>
                                <br>
                                <div class="row mb-3">
                                    <label class="col-sm-2 col-form-label">Education</label>
                                    <div class="col-sm-10">
                                        {{ form.educations }}
                                    </div>
                                </div>
                                <br>
                                <div class="row mb-3">
                                    <label class="col-sm-2 col-form-label">Categories</label>
                                    <div class="col-sm-10">
                                        {{ form.categories }}
                                    </div>
                                </div>
                                <br>

                                <div class="row mb-3">
                                    <label class="col-sm-2 col-form-label">Add worker</label>
                                    <div class="col-sm-10">
                                        <button type="submit" class="btn btn-primary">Submit</button>
                                    </div>
                                </div>

                            </form><!-- End General Form Elements -->

                        </div>
                    </div>

                </div>
            </div>
        </section>

    </main><!-- End #main -->


{% endblock content %}

app/templates/tasks/delete_task.html
{% extends "dashboard-base.html" %}

{% block content %}

    <main id="main" class="main">

        <div class="pagetitle">
            <h1>Modal</h1>
            <nav>
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href={% url 'home' %}>Home</a></li>
                    <li class="breadcrumb-item"><a href={% url 'management:dashboard' %}>Dashobard</a></li>
                    <li class="breadcrumb-item"><a href={% url 'tasks:list' %}>Tasks</a></li>
                    <li class="breadcrumb-item active">Delete</li>
                </ol>
            </nav>
        </div><!-- End Page Title -->

        <section class="section">
            <div class="row">
                <div class="col-lg-9">
                    <div class="card">
                        <div class="card-body">
                            <h5 class="card-title"><i class="bi bi-trash-fill"></i> Delete Task</h5>
                            <p>Are you sure you want to delete Task {{ task.title }}</p>


                            <form method="POST">
                                {% csrf_token %}
                                <input type="submit" class="btn btn-danger" data-bs-toggle="modal"
                                       data-bs-target="#basicModal" value="Delete Task"/>
                                &nbsp;
                                &nbsp;
                                &nbsp;
                                &nbsp;
                                &nbsp;
                                <a href="{% url 'tasks:list' %}"
                                   class="btn btn-primary">
                                    Back to Table
                                </a>
                            </form>
                        </div>
                    </div>
                </div>

            </div>
        </section>

    </main><!-- End #main -->


{% endblock content %}

app/templates/tasks/list_tasks.html
{% extends "dashboard-base.html" %}


{% block content %}

    <main id="main" class="main">
        <div class="pagetitle">
            <h1>Tasks Table</h1>
            <nav>
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href={% url 'home' %}>Home</a></li>
                    <li class="breadcrumb-item"><a href={% url 'management:dashboard' %}>Dashobard</a></li>
                    <li class="breadcrumb-item">Tasks</li>
                </ol>
            </nav>
        </div><!-- End Page Title -->

        <section class="section">
            <div class="row">
                <div class="col-lg-12">
                    <div class="card">
                        <div class="card-body">

                            <!-- Table with stripped rows -->
                            <table class="table datatable">
                                <thead>
                                <tr>
                                    <th scope="col" data-sortable="false">#</th>
                                    <th scope="col" data-sortable="false">Status</th>
                                    <th scope="col" data-sortable="false">Title</th>
                                    <th scope="col" data-sortable="false">Deadline</th>
                                    <th scope="col" data-sortable="false">Assigned To</th>
                                    <th scope="col" data-sortable="false">Actions</th>
                                </tr>
                                </thead>
                                <tbody>
                                {% for task in object_list %}
                                    <tr>
                                        <th scope="row">{{ task.id }}</th>
                                        <td>
                                            {% if task.status == "OPEN" %}
                                                <span class="badge bg-warning">  {{ task.status }} </span>
                                            {% elif task.status == "DONE" %}
                                                <span class="badge bg-success">Done</span>
                                            {% elif task.status == "PROGRESS" %}
                                                <span class="badge bg-danger">Progress</span>
                                            {% endif %}
                                        </td>

                                        <td>
                                            {{ task.title }}
                                        </td>

                                        <td>
                                            {{ task.deadline }}
                                        </td>

                                        <td>
                                            {% if task.assigned_to %}
                                                {{ task.assigned_to }}
                                            {% else %}
                                                No one
                                            {% endif %}
                                        </td>

                                        <td>
                                            <a href={% url 'tasks:details' task.id %}>
                                                <i class="bi bi-eye-fill"></i>
                                            </a>&nbsp;&nbsp;


                                            <a href={% url 'tasks:update' task.id %}>
                                                <i class="bi bi-pencil-fill"></i>
                                            </a>&nbsp;&nbsp;

                                            <a href={% url 'tasks:delete' task.id %}>
                                                <i class="bi bi-trash-fill"></i>
                                            </a>
                                        </td>

                                    </tr>
                                {% endfor %}

                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </section>

    </main><!-- End #main -->

{% endblock content %}

app/templates/tasks/task_details.html
{% extends "dashboard-base.html" %}
{% load static %}


{% block content %}
    <main id="main" class="main">
        <div class="pagetitle">
            <h1>Task Details</h1>
            <nav>
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href={% url 'home' %}>Home</a></li>
                    <li class="breadcrumb-item"><a href={% url 'management:dashboard' %}>Dashobard</a></li>
                    <li class="breadcrumb-item"><a href={% url 'tasks:list' %}>Tasks</a></li>
                    <li class="breadcrumb-item active">Details</li>
                </ol>
            </nav>
        </div>

        <section class="section profile">
            <div class="row">
                <div class="col-xl-4">

                    <div class="card">
                        <div class="card-body profile-card pt-4 d-flex flex-column align-items-center">
                            <img src="{% static 'img/task-icon.png' %}" alt="Profile" class="rounded-circle">
                            <h2>{{ title }}</h2>
                        </div>
                    </div>

                </div>

                <div class="col-xl-8">

                    <div class="card">
                        <div class="card-body pt-3">
                            <!-- Bordered Tabs -->
                            <ul class="nav nav-tabs nav-tabs-bordered">

                                <li class="nav-item">
                                    <button class="nav-link active" data-bs-toggle="tab"
                                            data-bs-target="#profile-overview">Overview
                                    </button>
                                </li>
                                <li class="nav-item">
                                    <button class="nav-link" data-bs-toggle="tab" data-bs-target="#profile-skills">
                                        Skills
                                    </button>
                                </li>
                                <li class="nav-item">
                                    <button class="nav-link" data-bs-toggle="tab" data-bs-target="#profile-educations">
                                        Educations
                                    </button>
                                </li>
                                <li class="nav-item">
                                    <button class="nav-link" data-bs-toggle="tab" data-bs-target="#profile-edit">
                                        Assign To
                                    </button>
                                </li>


                            </ul>
                            <div class="tab-content pt-2">
                                <div class="tab-pane fade show active profile-overview" id="profile-overview">
                                    <h5 class="card-title">{{ title }}</h5>
                                    <p class="small fst-italic">{{ description }}</p>
                                    <h5 class="card-title">Task Details</h5>


                                    <div class="row">
                                        <div class="col-lg-3 col-md-4 label">Statue</div>
                                        <div class="col-lg-4 col-md-4  badge bg-warningnord">{{ status }}</div>
                                    </div>


                                    <div class="row">
                                        <div class="col-lg-3 col-md-4 label">Deadline</div>
                                        <div class="fs-6 col-lg-4 col-md-4 col-sm-4 badge bg-danger">{{ deadline }}</div>
                                    </div>

                                </div>
                                <div class="tab-pane fade profile-edit pt-3" id="profile-skills">

                                    {% for category in categories %}
                                        <span class="fs-6 mb-3 {% cycle 'badge bg-primary'  'badge bg-secondary'   'badge bg-danger' 'badge bg-warning text-dark' 'badge bg-info text-dark' %}">
                                               {{ category }}
                                        </span>
                                    {% endfor %}
                                </div>
                                <div class="tab-pane fade profile-edit pt-3" id="profile-educations">

                                    {% for education in educations %}
                                        <span class="fs-6 mb-3 {% cycle 'badge bg-primary'  'badge bg-secondary'   'badge bg-danger' 'badge bg-warning text-dark' 'badge bg-info text-dark' %}">
                                               {{ education }}
                                        </span>
                                    {% endfor %}
                                </div>
                                <div class=" tab-pane fade profile-edit pt-3" id="profile-edit">

                                    {% if assigned_to %}
                                        <span class="fs-6 mb-3 badge bg-primary">
                                             {{ assigned_to.first_name }} {{ assigned_to.last_name }}
                                        </span>
                                    {% else %}
                                        <span class="fs-6 mb-3 badge bg-danger">
                                            None
                                            </span>
                                    {% endif %}
                                </div>

                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </section>

    </main><!-- End #main -->

{% endblock content %}

app/templates/tasks/update_task.html
{% extends "dashboard-base.html" %}


{% block content %}

    <main id="main" class="main">

        <div class="pagetitle">
            <h1>Update Task</h1>
            <nav>
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href={% url 'home' %}>Home</a></li>
                    <li class="breadcrumb-item"><a href={% url 'management:dashboard' %}>Dashobard</a></li>
                    <li class="breadcrumb-item"><a href={% url 'tasks:list' %}>Tasks</a></li>
                    <li class="breadcrumb-item active">Update Task</li>
                </ol>
            </nav>
        </div><!-- End Page Title -->

        <section class="section">
            <div class="row">
                <div class="col-lg-2"></div>
                <div class="col-lg-8">

                    <div class="card">
                        <div class="card-body">
                            <h5 class="card-title">Update Task Form</h5>

                            <!-- General Form Elements -->
                            <form method="post">
                                {% csrf_token %}
                                <div class="row mb-3">
                                    <label for="inputText" class="col-sm-2 col-form-label">Title</label>
                                    <div class="col-sm-10">
                                        {{ form.title }}
                                    </div>
                                </div>
                                <div class="row mb-3">
                                    <label for="inputText" class="col-sm-2 col-form-label">Description</label>
                                    <div class="col-sm-10">
                                        {{ form.description }}
                                    </div>
                                </div>

                                <br>
                                <div class="row mb-3">
                                    <label for="inputDate" class="col-sm-2 col-form-label">Dead Line</label>
                                    <div class="col-sm-10">
                                        {{ form.deadline }}
                                    </div>
                                </div>
                                <br>


                                <br>
                                <fieldset class="row mb-3">
                                    <legend class="col-form-label col-sm-2 pt-0">Status</legend>
                                    <div class="col-sm-10">
                                        {{ form.status }}
                                    </div>
                                </fieldset>
                                <br>
                                <div class="row mb-3">
                                    <label class="col-sm-2 col-form-label">Education</label>
                                    <div class="col-sm-10">
                                        {{ form.educations }}
                                    </div>
                                </div>
                                <br>
                                <div class="row mb-3">
                                    <label class="col-sm-2 col-form-label">Categories</label>
                                    <div class="col-sm-10">
                                        {{ form.categories }}
                                    </div>
                                </div>
                                <br>

                                <div class="row mb-3">
                                    <label class="col-sm-2 col-form-label">Update worker</label>
                                    <div class="col-sm-10">
                                        <button type="submit" class="btn btn-primary">Submit</button>
                                    </div>
                                </div>

                            </form><!-- End General Form Elements -->

                        </div>
                    </div>

                </div>
            </div>
        </section>

    </main><!-- End #main -->


{% endblock content %}