app/accounts/urls.py
from . import views
from django.urls import path

app_name = 'accounts'

urlpatterns = [

    path('signin', views.SigninView.as_view(), name='signin'),
    path('signup', views.SignupView.as_view(), name='signup'),
    path('logout', views.LogoutView.as_view(), name='logout'),
    path('profile', views.ProfileView.as_view(), name='profile'),
    path('change-password', views.ChangePasswordView.as_view(), name='change-password'),
    path('edit-profile', views.EditProfileView.as_view(), name='edit-profile'),

]

app/categories/urls.py
from . import views
from django.urls import path

app_name = 'categories'

urlpatterns = [

    path('', views.CategoryListView.as_view(), name='list'),
    path('create', views.CategoryCreateView.as_view(), name='create'),
    path('update/<int:pk>', views.CategoryUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', views.CategoryDeleteView.as_view(), name='delete'),

]

app/core/urls.py
from . import views
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    # Admin
    path('admin/', admin.site.urls),

    # Basic
    path('', views.HomeView.as_view(), name='home'),
    path('faq/', views.FAQView.as_view(), name='f-a-q'),

    # Apps
    path('tasks/', include('tasks.urls')),
    path('workers/', include('workers.urls')),
    path('accounts/', include('accounts.urls')),
    path('management/', include('management.urls')),
    path('categories/', include('categories.urls')),
    path('educations/', include('educations.urls')),
    path('presentation', views.PresentationView.as_view(), name='presentation'),
]

if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/tasks/urls.py
from . import views
from django.urls import path

app_name = 'tasks'

urlpatterns = [

    path('', views.TaskListView.as_view(), name='list'),
    path('create', views.TaskCreateView.as_view(), name='create'),
    path('<str:pk>', views.TaskDetailsView.as_view(), name='details'),
    path('update/<str:pk>', views.TaskUpdateView.as_view(), name='update'),
    path('delete/<str:pk>', views.TaskDeleteView.as_view(), name='delete'),

]

app/workers/urls.py
from . import views
from django.urls import path

app_name = 'workers'

urlpatterns = [
    path('', views.WorkerListView.as_view(), name='list'),
    path('create', views.WorkerCreateView.as_view(), name='create'),
    path('<str:pk>', views.WorkerDetailsView.as_view(), name='details'),
    path('update/<str:pk>', views.WorkerUpdateView.as_view(), name='update'),
    path('delete/<str:pk>', views.WorkerDeleteView.as_view(), name='delete'),
]

app/templates/partials/dashboard-header.html
{% load static %}
<header id="header" class="header fixed-top d-flex align-items-center">

    <div class="d-flex align-items-center justify-content-between">
        <a href="{% url 'home' %}" class="logo d-flex align-items-center">
            <img src="{% static 'img/logo.png' %}" alt="">

            <span class="d-none d-lg-block">MaxMatching</span>
        </a>
        <i class="bi bi-list toggle-sidebar-btn"></i>
    </div><!-- End Logo -->


    <nav class="header-nav ms-auto">
        <ul class="d-flex align-items-center">
            <li class="nav-item dropdown pe-3">
                <a class="nav-link nav-profile d-flex align-items-center pe-0" href="#" data-bs-toggle="dropdown">
                    {% if user.profile.logo %}
                        <img src="{% get_media_prefix %}{{ user.profile.logo }}" alt="logo"/>
                    {% else %}
                        <img src="{% static 'img/default-company-logo.png' %}" alt="logo">
                    {% endif %}

                    <span class="d-none d-md-block dropdown-toggle ps-2">

                         {% if user.profile.name %}
                             {{ user.profile.name }}
                         {% else %}
                             {{ user.username }}
                         {% endif %}
                    </span>
                </a><!-- End Profile Iamge Icon -->
                <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow profile">
                    <li class="dropdown-header">
                        {% if user.profile.name %}
                            <h6> {{ user.profile.name }}</h6>
                        {% else %}
                            <h6>-</h6>
                        {% endif %}
                        <span>{{ user.username }}</span>
                    </li>
                    <li>
                        <hr class="dropdown-divider">
                    </li>
                    <li>
                        <a class="dropdown-item d-flex align-items-center" href="{% url 'accounts:profile' %}">
                            <i class="bi bi-gear"></i>
                            <span>Account Settings </span>
                        </a>
                    </li>

                    <li>
                        <hr class="dropdown-divider">
                    </li>

                    <li>
                        <hr class="dropdown-divider">
                    </li>

                    <li>
                        <hr class="dropdown-divider">
                    </li>

                    <li>
                        <a class="dropdown-item d-flex align-items-center" href="{% url 'accounts:logout' %}">
                            <i class="bi bi-box-arrow-right"></i>
                            <span>Sign Out</span>
                        </a>
                    </li>

                </ul><!-- End Profile Dropdown Items -->
            </li><!-- End Profile Nav -->

        </ul>
    </nav><!-- End Icons Navigation -->

</header><!-- End Header -->

app/templates/partials/footer.html
<!-- ======= Footer ======= -->
<footer id="footer" class="footer">
    <div class="copyright">
        &copy; Copyright <strong><span>MaxMatching</span></strong>. All Rights Reserved
    </div>
    <div class="credits">

        Designed by <a href="https://www.svuonline.org/" target="_blank">Syrian Virtual University</a>
    </div>
</footer><!-- End Footer -->

app/templates/partials/sidebar.html
<aside id="sidebar" class="sidebar">

    <ul class="sidebar-nav" id="sidebar-nav">

        <li class="nav-item">
            <a class="nav-link collapsed" href="{% url 'management:dashboard' %}">
                <i class="bi bi-grid-fill"></i>
                <span>Dashboard</span>
            </a>
        </li><!-- End Dashboard Nav -->


        <li class="nav-item">
            <a class="nav-link collapsed" data-bs-target="#educations-nav" data-bs-toggle="collapse" href="#">
                <i class="bi bi-mortarboard-fill"></i><span>Educations</span><i
                    class="bi bi-chevron-down ms-auto"></i>
            </a>
            <ul id="educations-nav" class="nav-content collapse " data-bs-parent="#sidebar-nav">
                <li>
                    <a href="{% url 'educations:list' %}">
                        <i class="bi bi-circle"></i><span>Table</span>
                    </a>
                </li>

            </ul>
        </li><!-- End Educations Nav -->

        <li class="nav-item">
            <a class="nav-link collapsed" data-bs-target="#categories-nav" data-bs-toggle="collapse" href="#">
                <i class="bi bi-tags-fill"></i><span>Categories</span><i
                    class="bi bi-chevron-down ms-auto"></i>
            </a>
            <ul id="categories-nav" class="nav-content collapse " data-bs-parent="#sidebar-nav">
                <li>
                    <a href="{% url 'categories:list' %}">
                        <i class="bi bi-circle"></i><span>Table</span>
                    </a>
                </li>
            </ul>
        </li><!-- End Categories Nav -->


        <li class="nav-item">
            <a class="nav-link collapsed" data-bs-target="#tables-nav" data-bs-toggle="collapse" href="#">
                <i class="bi bi-person-badge-fill"></i><span>Workers</span><i
                    class="bi bi-chevron-down ms-auto"></i>
            </a>
            <ul id="tables-nav" class="nav-content collapse " data-bs-parent="#sidebar-nav">

                <li>
                    <a href="{% url 'workers:create' %}">
                        <i class="bi bi-circle"></i><span>Add new worker</span>
                    </a>
                </li>
                <li>
                    <a href="{% url 'workers:list' %}">
                        <i class="bi bi-circle"></i><span>Table</span>
                    </a>
                </li>

            </ul>
        </li><!-- End Workers Nav -->

        <li class="nav-item">
            <a class="nav-link collapsed" data-bs-target="#icons-nav" data-bs-toggle="collapse" href="#">
                <i class="bi bi-wrench-adjustable"></i><span>Tasks</span><i

                    class="bi bi-chevron-down ms-auto"></i>
            </a>

            <ul id="icons-nav" class="nav-content collapse " data-bs-parent="#sidebar-nav">
                <li>
                    <a href="{% url 'tasks:create' %}">
                        <i class="bi bi-circle"></i><span>Add new Task</span>
                    </a>
                </li>
                <li>
                    <a href="{% url 'tasks:list' %}">
                        <i class="bi bi-circle"></i><span>Table</span>
                    </a>
                </li>

            </ul>
        </li><!-- End Tasks Nav -->

        <li class="nav-item">
            <a class="nav-link collapsed" data-bs-target="#charts-nav" data-bs-toggle="collapse" href="#">
                <i class="bi bi-graph-up"></i><span>Task Assignment</span><i
                    class="bi bi-chevron-down ms-auto"></i>
            </a>
            <ul id="charts-nav" class="nav-content collapse " data-bs-parent="#sidebar-nav">
                <li>
                    <a href="{% url 'management:task-assigner' %}">
                        <i class="bi bi-circle"></i><span>Tasks Assigner</span>
                    </a>
                </li>
                <li>
                    <a href="{% url 'management:matching-result' %}">
                        <i class="bi bi-circle"></i><span>Matching Result</span>
                    </a>
                </li>

                <li>
                    <a href="{% url 'management:matching-history' %}">
                        <i class="bi bi-circle"></i><span>Matching History</span>
                    </a>
                </li>


            </ul>
        </li><!-- End Charts Nav -->
        {% if request.user.is_superuser %}
            <li class="nav-item">
                <a class="nav-link collapsed" href="{% url 'presentation' %}">
                    <i class="bi bi-easel2-fill"></i>
                    <span>Presentation</span>
                </a>
            </li>
        {% endif %}
        <li class="nav-heading">WebSite</li>

        <li class="nav-item">
            <a class="nav-link collapsed" href="{% url 'home' %}">
                <i class="bi bi-house"></i>
                <span>Home</span>
            </a>
        </li><!-- End F.A.Q Page Nav -->

        <li class="nav-item">
            <a class="nav-link collapsed" href="{% url 'f-a-q' %}">
                <i class="bi bi-question-circle"></i>
                <span>F.A.Q</span>
            </a>
        </li><!-- End F.A.Q Page Nav -->

        <li class="nav-item">
            <a class="nav-link collapsed" href="{% url 'management:contact-us' %}">
                <i class="bi bi-envelope"></i>
                <span>Contact</span>
            </a>
        </li><!-- End Contact Page Nav -->

        <li class="nav-item">
            <a class="nav-link collapsed" href="{% url 'accounts:logout' %}">
                <i class="bi bi-box-arrow-in-left"></i>
                <span>Logout</span>
            </a>
        </li><!-- End Login Page Nav -->


    </ul>

</aside><!-- End Sidebar-->

app/templates/partials/site-footer.html
{% load static %}
<footer id="footer">
    <div class="container">
        <div class="row d-flex align-items-center">
            <div class="col-lg-6 text-lg-left text-center">
                <div class="copyright">
                    &copy; Copyright <strong>Max Matching</strong>. All Rights Reserved
                </div>
                <div class="credits">
                    Designed by <a href="https://www.svuonline.org/" target="_blank">Syrian Virtual University</a>
                </div>
            </div>
            <div class="col-lg-6">
                <nav class="footer-links text-lg-right text-center pt-2 pt-lg-0">

                    <a href="{% url 'home' %}" class="scrollto">Home</a>
                    <a href="{% url 'management:dashboard' %}" class="scrollto">Dashboard</a>
                    <a href="{% url 'f-a-q' %}">FAQ</a>
                    <a href="{% url 'management:contact-us' %}">Contact</a>

                </nav>
            </div>
        </div>
    </div>
</footer>

app/templates/partials/site-header.html
{% load static %}
<header id="header" class="fixed-top d-flex align-items-center">
    <div class="container d-flex align-items-center justify-content-between">
        <div class="logo">
            <h1>

                <a href={% url 'home' %}> <img src="{% static 'img/logo.png' %}" alt="Profile">&nbsp; Max Matching</a>
            </h1>
        </div>
        <nav id="navbar" class="navbar">
            <ul>
                <li><a class="nav-link scrollto active" href="{% url 'home' %}">Home</a></li>
                <li><a class="nav-link scrollto" href="{% url 'management:dashboard' %}">Dashboard</a></li>
                <li><a class="nav-link scrollto" href="{% url 'f-a-q' %}">FAQ</a></li>
                <li><a class="nav-link scrollto" href="{% url 'management:contact-us' %}">Contact</a></li>



                {% if not user.is_authenticated %}
                    <li><a class="getstarted scrollto" href="{% url 'accounts:signin' %}">Login</a></li>
                {% else %}
                    <li><a class="getstarted scrollto" href="{% url 'accounts:profile' %}">

                        {% if  user.profile.name %}
                            {{ user.profile.name }}
                        {% else %}
                            {{ user.username }}
                        {% endif %}
                    </a>
                    </li>
                {% endif %}
            </ul>
            <i class="bi bi-list mobile-nav-toggle"></i>
        </nav>
    </div>
</header>